### ISSUE TITLE
Week 2 - Assignment #1 - Lab Git

### ISSUE THREAD

**Issue by mxistrissongpanya-matc** [madisoncollege-it-programs/python-scripting-mxistrissongpanya-matc#1] opened 2022-09-12 01:08 UTC

**Comment by mxistrissongpanya-matc** [comment] 2022-09-12 01:56
!usr/bin/env python 3
#Author: Max Songpanya

#This is my first python script and I will output newly learned commands.

My_full_name = "Max Songpanya"
My_age = 20

print(f"My name is {My_full_name} and I am {My_age} years old. This is my first script using formatting string.")


#I tried to commit, but were unable to. please accept this for now and we can talk about further directions.

**Comment by cethenmc** [comment] 2022-09-15 01:32
Hi, Max.  I will not deduct points as you are almost there, but it is absolutely critical for you to understand the github content.  All code will be turned in this way.  If you are still having issues, then please consider setting an appointment with me through Blackboard.  If you cannot find a time that works for you then, please let me know and we can work something out.  ~Chris

**Comment by cethenmc** [comment] 2022-09-22 03:40
Maxwell - I await your reply to tell me when this assignment is ready.  I will add a 0 to the grade book for now, but I need you to complete this correctly for credit.

**Comment by cethenmc** [comment] 2022-09-22 03:49
Looks like Issue ticket #1 and #2 are for the same script.  Not sure how we got two issues out here.

**Comment by cethenmc** [comment] 2022-10-04 03:46
I renamed this Issue to be more fitting:  Week 2 - Assignment #1.

This lab with the Getting started with GitHub assignment.  It looks like you tried to do this assignment in Week 1.  However, you did not do this exercise correctly.  You should redo this completely yet.  Please don't hesitate to reach out if you have questions.  Start by trying to book time with me through Blackboard > Instructor Contact.  If you cannot find a time that works that way, then please reach out via email telling me that nothing fits, and we can work out another time.

Thanks.

Chris

**Comment by cethenmc** [comment] 2022-10-04 03:47
I forgot to add that I marked it as 4 out of 8 for now, until you do it again as intended.  It can be confusing so please do reach out if you need a hand.

**Comment by cethenmc** [comment] 2022-10-30 23:43
I will give you until Friday on this one. Otherwise, you will lock in the 4 out of 8 that I have recorded.

**Comment by cethenmc** [comment] 2022-11-16 22:19
Locked in this grade for the lab.

**Closed by cethenmc** 2022-11-16 22:19 UTC
